//
//  RTRButtonStyle.m
//  Rent The Runway
//
//  Created by Billy tobon on 2/16/15.
//  Copyright (c) 2015 Rent The Runway. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "RTRButtonStyle.h"


@implementation RTRButtonStyle

#pragma mark Cache

static UIColor* _iconColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _iconColor = [UIColor colorWithRed: 0.078 green: 0.129 blue: 0.302 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)iconColor { return _iconColor; }

#pragma mark Drawing Methods

+ (void)drawRateButtonWithRadius: (CGFloat)radius title: (NSString*)title pressed: (BOOL)pressed
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.5 green: 0.5 blue: 0.5 alpha: 0.157];

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(31.5, 20.5, 200, 54.5);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: radius];
    [UIColor.whiteColor setFill];
    [rectanglePath fill];
    [RTRButtonStyle.iconColor setStroke];
    rectanglePath.lineWidth = 3;
    [rectanglePath stroke];
    NSMutableParagraphStyle* rectangleStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    rectangleStyle.alignment = NSTextAlignmentRight;

    NSDictionary* rectangleFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"HelveticaNeue-Medium" size: 26], NSForegroundColorAttributeName: RTRButtonStyle.iconColor, NSParagraphStyleAttributeName: rectangleStyle};

    [title drawInRect: CGRectInset(rectangleRect, 34, 9) withAttributes: rectangleFontAttributes];


    //// Star Drawing
    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(59.5, 33.5)];
    [starPath addLineToPoint: CGPointMake(62.52, 42.34)];
    [starPath addLineToPoint: CGPointMake(71.86, 42.48)];
    [starPath addLineToPoint: CGPointMake(64.39, 48.09)];
    [starPath addLineToPoint: CGPointMake(67.14, 57.02)];
    [starPath addLineToPoint: CGPointMake(59.5, 51.64)];
    [starPath addLineToPoint: CGPointMake(51.86, 57.02)];
    [starPath addLineToPoint: CGPointMake(54.61, 48.09)];
    [starPath addLineToPoint: CGPointMake(47.14, 42.48)];
    [starPath addLineToPoint: CGPointMake(56.48, 42.34)];
    [starPath closePath];
    [RTRButtonStyle.iconColor setFill];
    [starPath fill];
    [RTRButtonStyle.iconColor setStroke];
    starPath.lineWidth = 1;
    [starPath stroke];


    if (pressed)
    {
        //// Rectangle 2 Drawing
        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(31.5, 20.5, 200.5, 54.5) cornerRadius: radius];
        [color setFill];
        [rectangle2Path fill];
    }
}

@end
