//
//  RTRButtonStyle.h
//  Rent The Runway
//
//  Created by Billy tobon on 2/16/15.
//  Copyright (c) 2015 Rent The Runway. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RTRButtonStyle : NSObject

// Colors
+ (UIColor*)iconColor;

// Drawing Methods
+ (void)drawRateButtonWithRadius: (CGFloat)radius title: (NSString*)title pressed: (BOOL)pressed;

@end
